name: Keep Render App Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s -o /dev/null -w "%{http_code}" https://drop-dead-game.onrender.com
